### DISCUSSION TITLE
Variables

### DISCUSSION THREAD

**Discussion by Rykath** [redmod-team/profit#163] [Ideas]
Gathering a few ideas and observations related to *Variables*

## Requirements
* the target simulation takes several parameters and returns several output variables
* the parameters follow a specified distribution
* for Active Learning and flexible number of points, the samples need to be drawn iteratively
* Variables and Encoders are connected: e.g. LogUniform usually requires a LogEncoder for a good fit
* Some inputs/outputs are vector/matrix/tensor valued
* Some inputs/outputs are functions in theory, vectors over support points or a combination of basis functions in practice
  * for fitting and analysis, a dimensionality reduction is vital

## Current Status
* Input, Independent & Output
  * Input: Constant, Linear, Uniform, LogUniform, Normal, Halton, Active Learning
* only linearly spaced independent variables
* designed for continuous values only

## Ideas for Improvement
* separate the specification of the sampling distribution from the sampling method
  * Distribution/Transformation/Encoder: Linear / Uniform, Logarithmic / LogUniform, Gaussian → #160 
  * Method: Grid, Random (uniform), Halton (quasi-random), Constant/Fixed (could be multiple)
  * Advantage: Sampling method can be changed easily, Encoder mostly depends on the spacing, adding new distributions or methods can be done independently
  * Connection: Each sampling method assumes a linear spacing, a transformation / encoder is used to map it to the specified distribution
* four types of variables
  * Input - relevant dimensions for sampling and active learning
  * Output
  * Constant - ignored in Surrogate but usable in the Worker, possibly allow a list of constants and each step shall be run for each set of constants in parallel?
  * Independent - fixed values, expanded to axis or reduced to index in Surrogate
* Active Learning is a separate section, and not a method
  * uses the sampling method for the warmup phase
  * searches and proposes new samples for the specified variables, takes the sampling method for all others
* load user specified parameters and old data
* discrete variables
* function valued variables
  * high dimensionality
    * high number of support points
    * support points follow a spacing / distribution themselves, usually continuous
  * best practice: decomposition / dimensionality reduction
  * alternative for function outputs: surrogate treats the independent dimension just as another input dimension
  * for inputs: how to specify constraints, how to sample
  * idea (by Maximilian): specify `import(profiles.nc)` to load example profiles, then run a PCA and sample from the components
* tensor valued variables
  * low dimensionality - indices, discrete
  * can be uncorrelated
  * sometimes dimensionality reduction is possible
  * shouldn’t need an additional index variable - only specify shape
* some variables are connected differently
  * most prominent: mean & error
  * Use case: heteroscedastic noise
  * should this relation be specified? If so, how?

## Proposed example configuration
```yaml
variables:
  u: Uniform(min, max)  # ~ Linear
  v: Logarithmic(min, max, base=10)  # ~ Log, LogUniform
  x: Gaussian(mean, std)  # ~ Normal
  y: - Logarithmic
     - Gaussian(mean, std)  # ~ LogGaussian
  f: - import(profile.nc) 
     - PCA(n or tol)
sampling:
  n: 10
  Random: u, v  # ~ Uniform
  Halton: x, y
  Grid:  f
activelearning:
  n: 30
  variables: x, y, f  # u, v sampled randomly
```
