### ISSUE TITLE
mockup fails on mpcdf cluster

### ISSUE THREAD

**Issue by Rykath** [redmod-team/profit#128]
Trying to run `example/mockup` with the (modified) `slurm.yaml` configuration gives the following error:

```
Traceback (most recent call last):
  File "/u/calbert/.local/bin/profit-worker", line 33, in <module>
    sys.exit(load_entry_point('profit', 'console_scripts', 'profit-worker')())
  File "/raven/u/calbert/src/profit/profit/run/worker.py", line 291, in main
    worker = Worker.from_env()
  File "/raven/u/calbert/src/profit/profit/run/worker.py", line 198, in from_env
    base_config = Config.from_file(checkenv('PROFIT_CONFIG_PATH'))
  File "/raven/u/calbert/src/profit/profit/run/worker.py", line 22, in checkenv
    raise RuntimeError
RuntimeError
```

@krystophny: could you pleae give me some more details on when this error occured? Was this just the output if you use `sbatch` manually or during normal invocation with `profit run slurm.yaml`?

**Comment by krystophny** [comment]
@Rykath it was with `profit run slurm.yaml` and with


`$ cat slurm.yaml`
```yaml
albert@raven01:~/src/profit/examples/mockup/study> cat slurm.yaml
# same as profit.yaml but using the SlurmRunner
ntrain: 30
variables:
    u: Uniform(4.7, 5.3)
    v: Uniform(0.55, 0.6)
    r: Independent
    f: Output
run:
    runner:
        class: slurm
        parallel: 10
        options:
            job-name: profit-mockup
            time: 00:00:10
            mem: 1G
            export: ALL
    interface:
        class: zeromq
        port: 9100
    include: ../mockup.py
    worker: mockup
```

**Comment by Rykath** [comment]
Then I'd suggest you try using a modified local configuration to further pinpoint the issue. Please modify `profit.yaml` by adding the `fork: false` line and then test `profit run`:

```yaml
run:
    runner:
        class: local
        parallel: 4
        sleep: 0
        fork: false
    include: ../mockup.py
    worker: mockup
```

This should tell us whether the issue is related to slurm or if there is a fundamental problem with this specific environment.

**Comment by krystophny** [comment]
Just checked `fork: false`, it runs without any issue.

**Comment by krystophny** [comment]
It could be that the earlier errors were related to me pressing CTRL+C while runs were not finished. Now I get a silent failure and only the last 8 logfiles show up. Is there a way to get verbose output? (we should allow this as an option anyway)

```
calbert@raven02:~/src/profit/examples/mockup/study> cat slurm-394163_21.out

=================================
Global information about the job:
=================================

Job owner: calbert(78358)
Job name:  profit-mockup
Node list: ravc2210
Job start: Tue May 25 11:16:53 CEST 2021
Job end:   Tue May 25 11:16:55 CEST 2021
Work dir:  /raven/u/calbert/src/profit/examples/mockup/study
Command:   /raven/u/calbert/src/profit/examples/mockup/study/slurm.bash



==========================================================================================
Information on jobsteps (Note: MaxRSS/AveRSS is the maximum/average over all
tasks of the per-task memory high-water marks; cf. "man sacct"):
==========================================================================================

       JobID    JobName NNodes NTasks  NCPUS       MaxRSS       AveRSS    Elapsed ExitCode
------------ ---------- ------ ------ ------ ------------ ------------ ---------- --------
394163_21    profit-mo+      1             2                             00:00:02      1:0
394163_21.0  profit-wo+      1      1      1        1.20M        1.20M   00:00:01      1:0

Maximum memory per node: 0.001233 GB (defined as MaxRSS*Ntasks/NNodes)
CPU utilization: 0 %
```

**Comment by krystophny** [comment]
... running `profit-worker` directly gives the same error:
```
calbert@raven02:~/src/profit/examples/mockup/study> profit-worker
PROFIT_CONFIG_PATH is not set
Traceback (most recent call last):
  File "/u/calbert/.local/bin/profit-worker", line 33, in <module>
    sys.exit(load_entry_point('profit', 'console_scripts', 'profit-worker')())
  File "/raven/u/calbert/src/profit/profit/run/worker.py", line 291, in main
    worker = Worker.from_env()
  File "/raven/u/calbert/src/profit/profit/run/worker.py", line 198, in from_env
    base_config = Config.from_file(checkenv('PROFIT_CONFIG_PATH'))
  File "/raven/u/calbert/src/profit/profit/run/worker.py", line 22, in checkenv
    raise RuntimeError
RuntimeError
```

**Comment by Rykath** [comment]
Yes running `profit_worker` directly is not supported as the environment variables (among them `PROFIT_CONFIG_PATH` and `PROFIT_RUN_ID`) are set by the Runner. I don't think it's necessary to run `profit-worker` directly as a user so I don't think it's worthwhile to change the `profit-worker` to use command line arguments instead (even thought it would be cleaner).

> Is there a way to get verbose output? (we should allow this as an option anyway)

There is the option `clean: false` which disables the automatic removal of generated files. Apart from that the most verbose mode should already be the default (controlled with different loglevels).

```yaml
run:
    clean: false
    runner:
        class: slurm
        parallel: 10
        options:
            job-name: profit-mockup
            time: 00:00:10
            mem: 1G
            export: ALL
```

Out of interest, does removing the `export: ALL` statement cause more problems?
